package main

import (
	"fmt"
	"pubtransport/passengers"
	"pubtransport/publictransport"
)

func main() {
	// plane := publictransport.NewPlane()
	fmt.Println("*********************************************")
	p := passengers.NewPassenger("Anastasiia", "Koriahina", 20)
	p1 := passengers.NewPassenger("Ivan", "Nahorniak", 36)
	p2 := passengers.NewPassenger("Bohdan", "Ferens", 40)
	// plane := publictransport.NewPlane()
	// fmt.Println("ADDING PASSENGERs")
	// plane.TakePassengers(p)
	// plane.TakePassengers(p1)
	// plane.TakePassengers(p2)
	// fmt.Println("*********************************************")
	fmt.Println(p)
	fmt.Println(p1)
	fmt.Println(p2)
	fmt.Println("*********************************************")
	// fmt.Println(plane.Passengers)
	// fmt.Println("DELETING PASSENGERs")
	// plane.DisembarkPassengers(p)
	// fmt.Println("*********************************************")
	// fmt.Println(p)
	// fmt.Println(p1)
	// fmt.Println(p2)
	// fmt.Println(plane.Passengers)

	// bus := publictransport.NewBus()
	// fmt.Println("*******************ADDING PASSENGERS***********************")
	// bus.TakePassengers(p2)
	// bus.TakePassengers(p1)
	// bus.TakePassengers(p)
	// fmt.Println(bus.Passengers)
	// fmt.Println("*******************DELETING PASSENGERS***********************")
	// bus.DisembarkPassengers(p)
	// bus.DisembarkPassengers(p1)
	// bus.DisembarkPassengers(p2)
	// fmt.Println(bus.Passengers)
	// fmt.Println(p)
	// fmt.Println(p1)
	// fmt.Println(p2)

	train := publictransport.NewTrain(7)
	fmt.Println("*****************ADDING PASSENGERS********************")
	train.TakePassengers(p)
	train.TakePassengers(p1)
	train.TakePassengers(p2)
	fmt.Println(train.Passengers)
	fmt.Println(p)
	fmt.Println(p1)
	fmt.Println(p2)
	fmt.Println("**********************DELETING PASSENGER*********************")
	train.DisembarkPassengers(p)
	train.DisembarkPassengers(p1)
	train.DisembarkPassengers(p2)
	fmt.Println(train.Passengers)
	fmt.Println(p)
	fmt.Println(p1)
	fmt.Println(p2)
}
